name: "Browsercore install"
description: "Install deps for the project browsercore"

runs:
  using: "composite"

  steps:
    - name: install v8
      shell: bash
      run: |
        mkdir -p vendor/zig-js-runtime/vendor/v8/${{env.ARCH}}/debug
        ln -s /usr/local/lib/libc_v8.a vendor/zig-js-runtime/vendor/v8/${{env.ARCH}}/debug/libc_v8.a

        mkdir -p vendor/zig-js-runtime/vendor/v8/${{env.ARCH}}/release
        ln -s /usr/local/lib/libc_v8.a vendor/zig-js-runtime/vendor/v8/${{env.ARCH}}/release/libc_v8.a

    - name: libiconv
      shell: bash
      run: |
        ln -s /usr/local/lib/libiconv vendor/libiconv

    - name: build mimalloc
      shell: bash
      run: make install-mimalloc

    - name: build netsurf
      shell: bash
      run: make install-netsurf
